# Usage: "cmake -P generate_client_settings.cmake -DCLIENT_SETTINGS_JSON_PATH=<path_to_client_settings.json> -DOFFLINE_MODE=<true_or_false>"
#
# Optional: -DDIRECT_CONNECT=<true_or_false> (defaults to OFFLINE_MODE)
#
# Direct connect mode means the client talks to a game server address the player
# types into the in-game menu (F2) instead of resolving it through the master
# API. That is what makes LAN, Radmin VPN, Hamachi, a home-hosted server and a
# public VPS/Docker deployment all work without any external service.

if(NOT DEFINED DIRECT_CONNECT)
    set(DIRECT_CONNECT ${OFFLINE_MODE})
endif()

# read current server-settings.json
if(EXISTS "${CLIENT_SETTINGS_JSON_PATH}")
    file(READ "${CLIENT_SETTINGS_JSON_PATH}" CLIENT_SETTINGS_JSON)
else()
    set(CLIENT_SETTINGS_JSON "{}")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-ip" "\"127.0.0.1\"")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-port" "7777")
endif()

if(DIRECT_CONNECT)
    # No master API, no account: the player picks the host in the F2 menu, and a
    # per-installation profile id is generated by the client (see
    # connectMenuService.ts). A profileId baked into the shipped settings would
    # be shared by every player and therefore by every character, so make sure
    # there is none.
    string(JSON has_game_data ERROR_VARIABLE dummy GET "${CLIENT_SETTINGS_JSON}" "gameData")
    if(has_game_data)
        string(JSON CLIENT_SETTINGS_JSON REMOVE "${CLIENT_SETTINGS_JSON}" "gameData")
    endif()
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "master" "\"\"")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-master-key" "null")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "directConnect" "true")
    # Nothing to ask the master API about
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-info-ignore" "true")
    # Set to true to skip the menu and dial the remembered address on startup
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "autoConnect" "false")
elseif(OFFLINE_MODE)
    set(profile_id "")
    string(JSON profile_id ERROR_VARIABLE dummy GET "${CLIENT_SETTINGS_JSON}" "gameData" "profileId")

    # check if profile_id is number
    if(NOT profile_id MATCHES "^[0-9]+$")
        set(profile_id 1)
    endif()

    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "gameData" "{ \"profileId\": ${profile_id} }")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "master" "\"\"")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-master-key" "null")
else()
    string(JSON CLIENT_SETTINGS_JSON REMOVE "${CLIENT_SETTINGS_JSON}" "gameData")
    string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "master" "\"https://gateway.skymp.net\"")

    # if ip in config is 127.0.0.1
    string(JSON server_ip ERROR_VARIABLE dummy GET "${CLIENT_SETTINGS_JSON}" "server-ip")
    if(server_ip STREQUAL "127.0.0.1")
        file(DOWNLOAD "https://api.ipify.org" "${CMAKE_CURRENT_BINARY_DIR}/ip.txt")
        file(READ "${CMAKE_CURRENT_BINARY_DIR}/ip.txt" ip)
        set(port 7777)
        string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-master-key" "\"${ip}:${port}\"")
    else()
        string(JSON CLIENT_SETTINGS_JSON SET "${CLIENT_SETTINGS_JSON}" "server-master-key" "null")
    endif()
endif()

file(WRITE "${CLIENT_SETTINGS_JSON_PATH}" "${CLIENT_SETTINGS_JSON}")
